### ISSUE TITLE
Possible backend bug

### ISSUE THREAD

**Issue by spwisner** [squad-lake-city/bucketlist#10]
When making a get request for all bucketlist items, the following prints in the console:

![image](https://cloud.githubusercontent.com/assets/13546265/23835443/f41783ca-073d-11e7-9068-5c0c501beebe.png)

Although this does not appear to affect functionality, it is probably due to the change that was made for completed field being changed to a boolean (from a number).

**Comment by cshea93** [comment]
I will give this a look, Steve.

**Comment by cshea93** [comment]
Changing the type="number" to type="hidden" in bucketlist.handlebars seems to have solved this warning.

**Comment by cshea93** [comment]
I can push my change and close this issue on confirmation from you, Steve.

**Comment by cshea93** [comment]
Upon further investigation, changing the value in handlebars seems to prevent the user from editing completion status...
