### ISSUE TITLE
Auth Forms

### ISSUE THREAD

**Issue by cshea93** [squad-lake-city/bucketlist#11]
A few potential bugs here I am going to look into. 

1) Sign-up seems to succeed even when password and password_confirmation DO NOT MATCH. 
...This may have been an issue from the beginning, but I believe I checked for that on Friday and it was working properly. 

2) The blue color of the forms make it impossible to see what the user is highlighting(because the default highlight color is also blue, on my computer at least.)

Just some stuff to check in on today.

**Comment by lbreguet** [comment]
I can add a function that can stop that from happening. It looks a little like this:
```
let password = document.getElementById("password"),
    password_confirmation = document.getElementById("password_confirmation");

  function validatePassword() {
    if (password.value !== password_confirmation.value) {
      password_confirmation.setCustomValidity("Passwords Don't Match!");
    } else {
      password_confirmation.setCustomValidity('');
    }
  }

  password.onchange = validatePassword;
  password_confirmation.onkeyup = validatePassword;
```
This actually isnt working

**Comment by cshea93** [comment]
Sign-up issue seems to be happening across all other Squads' deployed applications...trap bug perhaps?

**Comment by cshea93** [comment]
Fixed sign-up with a conditional to check that passwords match. Looks like someone else took care of the form color. /Thread.
